// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Generated by `scripts/codegen/dart_db_types.mjs` from
// `packages/types/src/database.ts` (the same shape that
// powers the web + admin clients).
//
// To regenerate:
//
//     node scripts/codegen/dart_db_types.mjs
//
// CI runs this script in --check mode and fails if the working
// copy is out of date.

// ignore_for_file: type=lint, public_member_api_docs

/// Mirror of `public.profiles` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class ProfilesRow {
  const ProfilesRow({
    required this.id,
    required this.email,
    this.fullName,
    this.avatarUrl,
    required this.plan,
    this.planExpiresAt,
    this.stripeCustomerId,
    required this.maxResumes,
    this.billingCountry,
    this.referralCode,
    this.referredBy,
    required this.marketingEmailsEnabled,
    required this.unsubscribeToken,
    required this.locale,
    required this.isDisabled,
    this.disabledReason,
    this.disabledAt,
    this.lastSeenAt,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String email;
  final String? fullName;
  final String? avatarUrl;
  final String plan;
  final String? planExpiresAt;
  final String? stripeCustomerId;
  final num maxResumes;
  final String? billingCountry;
  final String? referralCode;
  final String? referredBy;
  final bool marketingEmailsEnabled;
  final String unsubscribeToken;
  final String locale;
  final bool isDisabled;
  final String? disabledReason;
  final String? disabledAt;
  final String? lastSeenAt;
  final String createdAt;
  final String updatedAt;

  factory ProfilesRow.fromJson(Map<String, dynamic> json) {
    return ProfilesRow(
      id: json['id'] as String? ?? '',
      email: json['email'] as String? ?? '',
      fullName: json['full_name'] as String?,
      avatarUrl: json['avatar_url'] as String?,
      plan: json['plan'] as String? ?? '',
      planExpiresAt: json['plan_expires_at'] as String?,
      stripeCustomerId: json['stripe_customer_id'] as String?,
      maxResumes: (json['max_resumes'] as num?) ?? 0,
      billingCountry: json['billing_country'] as String?,
      referralCode: json['referral_code'] as String?,
      referredBy: json['referred_by'] as String?,
      marketingEmailsEnabled:
          json['marketing_emails_enabled'] as bool? ?? false,
      unsubscribeToken: json['unsubscribe_token'] as String? ?? '',
      locale: json['locale'] as String? ?? '',
      isDisabled: json['is_disabled'] as bool? ?? false,
      disabledReason: json['disabled_reason'] as String?,
      disabledAt: json['disabled_at'] as String?,
      lastSeenAt: json['last_seen_at'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'email': email,
      'full_name': fullName,
      'avatar_url': avatarUrl,
      'plan': plan,
      'plan_expires_at': planExpiresAt,
      'stripe_customer_id': stripeCustomerId,
      'max_resumes': maxResumes,
      'billing_country': billingCountry,
      'referral_code': referralCode,
      'referred_by': referredBy,
      'marketing_emails_enabled': marketingEmailsEnabled,
      'unsubscribe_token': unsubscribeToken,
      'locale': locale,
      'is_disabled': isDisabled,
      'disabled_reason': disabledReason,
      'disabled_at': disabledAt,
      'last_seen_at': lastSeenAt,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.resumes` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class ResumesRow {
  const ResumesRow({
    required this.id,
    required this.userId,
    required this.title,
    required this.slug,
    required this.templateId,
    required this.language,
    required this.isPublic,
    this.passwordHash,
    required this.hideFromSearch,
    required this.completionScore,
    this.customUrl,
    required this.viewsCount,
    this.theme,
    this.sectionOrder,
    this.sectionLabels,
    this.hiddenFields,
    required this.showEducationFirst,
    this.customSections,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String userId;
  final String title;
  final String slug;
  final String templateId;
  final String language;
  final bool isPublic;
  final String? passwordHash;
  final bool hideFromSearch;
  final num completionScore;
  final String? customUrl;
  final num viewsCount;
  final dynamic theme;
  final dynamic sectionOrder;
  final dynamic sectionLabels;
  final dynamic hiddenFields;
  final bool showEducationFirst;
  final dynamic customSections;
  final String createdAt;
  final String updatedAt;

  factory ResumesRow.fromJson(Map<String, dynamic> json) {
    return ResumesRow(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String? ?? '',
      title: json['title'] as String? ?? '',
      slug: json['slug'] as String? ?? '',
      templateId: json['template_id'] as String? ?? '',
      language: json['language'] as String? ?? '',
      isPublic: json['is_public'] as bool? ?? false,
      passwordHash: json['password_hash'] as String?,
      hideFromSearch: json['hide_from_search'] as bool? ?? false,
      completionScore: (json['completion_score'] as num?) ?? 0,
      customUrl: json['custom_url'] as String?,
      viewsCount: (json['views_count'] as num?) ?? 0,
      theme: json['theme'],
      sectionOrder: json['section_order'],
      sectionLabels: json['section_labels'],
      hiddenFields: json['hidden_fields'],
      showEducationFirst: json['show_education_first'] as bool? ?? false,
      customSections: json['custom_sections'],
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'user_id': userId,
      'title': title,
      'slug': slug,
      'template_id': templateId,
      'language': language,
      'is_public': isPublic,
      'password_hash': passwordHash,
      'hide_from_search': hideFromSearch,
      'completion_score': completionScore,
      'custom_url': customUrl,
      'views_count': viewsCount,
      'theme': theme,
      'section_order': sectionOrder,
      'section_labels': sectionLabels,
      'hidden_fields': hiddenFields,
      'show_education_first': showEducationFirst,
      'custom_sections': customSections,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.personal_info` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class PersonalInfoRow {
  const PersonalInfoRow({
    required this.id,
    required this.resumeId,
    this.fullName,
    this.jobTitle,
    this.bio,
    this.email,
    this.phone,
    this.phoneCountryCode,
    this.website,
    this.city,
    this.country,
    this.nationality,
    this.dateOfBirth,
    this.gender,
    this.maritalStatus,
    this.healthStatus,
    this.militaryService,
    this.avatarPath,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final String? fullName;
  final String? jobTitle;
  final String? bio;
  final String? email;
  final String? phone;
  final String? phoneCountryCode;
  final String? website;
  final String? city;
  final String? country;
  final String? nationality;
  final String? dateOfBirth;
  final String? gender;
  final String? maritalStatus;
  final String? healthStatus;
  final String? militaryService;
  final String? avatarPath;
  final dynamic ar;
  final dynamic en;

  factory PersonalInfoRow.fromJson(Map<String, dynamic> json) {
    return PersonalInfoRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      fullName: json['full_name'] as String?,
      jobTitle: json['job_title'] as String?,
      bio: json['bio'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      phoneCountryCode: json['phone_country_code'] as String?,
      website: json['website'] as String?,
      city: json['city'] as String?,
      country: json['country'] as String?,
      nationality: json['nationality'] as String?,
      dateOfBirth: json['date_of_birth'] as String?,
      gender: json['gender'] as String?,
      maritalStatus: json['marital_status'] as String?,
      healthStatus: json['health_status'] as String?,
      militaryService: json['military_service'] as String?,
      avatarPath: json['avatar_path'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'full_name': fullName,
      'job_title': jobTitle,
      'bio': bio,
      'email': email,
      'phone': phone,
      'phone_country_code': phoneCountryCode,
      'website': website,
      'city': city,
      'country': country,
      'nationality': nationality,
      'date_of_birth': dateOfBirth,
      'gender': gender,
      'marital_status': maritalStatus,
      'health_status': healthStatus,
      'military_service': militaryService,
      'avatar_path': avatarPath,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.education` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class EducationRow {
  const EducationRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.institution,
    this.degree,
    this.fieldOfStudy,
    this.startDate,
    this.endDate,
    this.description,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? institution;
  final String? degree;
  final String? fieldOfStudy;
  final String? startDate;
  final String? endDate;
  final String? description;
  final dynamic ar;
  final dynamic en;

  factory EducationRow.fromJson(Map<String, dynamic> json) {
    return EducationRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      institution: json['institution'] as String?,
      degree: json['degree'] as String?,
      fieldOfStudy: json['field_of_study'] as String?,
      startDate: json['start_date'] as String?,
      endDate: json['end_date'] as String?,
      description: json['description'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'institution': institution,
      'degree': degree,
      'field_of_study': fieldOfStudy,
      'start_date': startDate,
      'end_date': endDate,
      'description': description,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.experience` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class ExperienceRow {
  const ExperienceRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.company,
    this.jobTitle,
    this.startDate,
    this.endDate,
    required this.isCurrent,
    this.description,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? company;
  final String? jobTitle;
  final String? startDate;
  final String? endDate;
  final bool isCurrent;
  final String? description;
  final dynamic ar;
  final dynamic en;

  factory ExperienceRow.fromJson(Map<String, dynamic> json) {
    return ExperienceRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      company: json['company'] as String?,
      jobTitle: json['job_title'] as String?,
      startDate: json['start_date'] as String?,
      endDate: json['end_date'] as String?,
      isCurrent: json['is_current'] as bool? ?? false,
      description: json['description'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'company': company,
      'job_title': jobTitle,
      'start_date': startDate,
      'end_date': endDate,
      'is_current': isCurrent,
      'description': description,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.skills` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class SkillsRow {
  const SkillsRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    required this.name,
    this.level,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String name;
  final String? level;

  factory SkillsRow.fromJson(Map<String, dynamic> json) {
    return SkillsRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      name: json['name'] as String? ?? '',
      level: json['level'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'name': name,
      'level': level,
    };
  }
}

/// Mirror of `public.languages` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class LanguagesRow {
  const LanguagesRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    required this.languageName,
    this.fluency,
    required this.isSignLanguage,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String languageName;
  final String? fluency;
  final bool isSignLanguage;

  factory LanguagesRow.fromJson(Map<String, dynamic> json) {
    return LanguagesRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      languageName: json['language_name'] as String? ?? '',
      fluency: json['fluency'] as String?,
      isSignLanguage: json['is_sign_language'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'language_name': languageName,
      'fluency': fluency,
      'is_sign_language': isSignLanguage,
    };
  }
}

/// Mirror of `public.courses` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class CoursesRow {
  const CoursesRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.name,
    this.institution,
    this.startDate,
    this.endDate,
    required this.isCurrent,
    this.description,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? name;
  final String? institution;
  final String? startDate;
  final String? endDate;
  final bool isCurrent;
  final String? description;
  final dynamic ar;
  final dynamic en;

  factory CoursesRow.fromJson(Map<String, dynamic> json) {
    return CoursesRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      name: json['name'] as String?,
      institution: json['institution'] as String?,
      startDate: json['start_date'] as String?,
      endDate: json['end_date'] as String?,
      isCurrent: json['is_current'] as bool? ?? false,
      description: json['description'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'name': name,
      'institution': institution,
      'start_date': startDate,
      'end_date': endDate,
      'is_current': isCurrent,
      'description': description,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.projects` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class ProjectsRow {
  const ProjectsRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.name,
    this.url,
    this.startDate,
    this.endDate,
    required this.isCurrent,
    this.description,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? name;
  final String? url;
  final String? startDate;
  final String? endDate;
  final bool isCurrent;
  final String? description;
  final dynamic ar;
  final dynamic en;

  factory ProjectsRow.fromJson(Map<String, dynamic> json) {
    return ProjectsRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      name: json['name'] as String?,
      url: json['url'] as String?,
      startDate: json['start_date'] as String?,
      endDate: json['end_date'] as String?,
      isCurrent: json['is_current'] as bool? ?? false,
      description: json['description'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'name': name,
      'url': url,
      'start_date': startDate,
      'end_date': endDate,
      'is_current': isCurrent,
      'description': description,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.references` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class ReferencesRow {
  const ReferencesRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.name,
    this.email,
    this.phone,
    this.phoneCountryCode,
    this.description,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? name;
  final String? email;
  final String? phone;
  final String? phoneCountryCode;
  final String? description;
  final dynamic ar;
  final dynamic en;

  factory ReferencesRow.fromJson(Map<String, dynamic> json) {
    return ReferencesRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      name: json['name'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      phoneCountryCode: json['phone_country_code'] as String?,
      description: json['description'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'name': name,
      'email': email,
      'phone': phone,
      'phone_country_code': phoneCountryCode,
      'description': description,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.social_links` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class SocialLinksRow {
  const SocialLinksRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.url,
    this.linkType,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? url;
  final String? linkType;

  factory SocialLinksRow.fromJson(Map<String, dynamic> json) {
    return SocialLinksRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      url: json['url'] as String?,
      linkType: json['link_type'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'url': url,
      'link_type': linkType,
    };
  }
}

/// Mirror of `public.hobbies` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class HobbiesRow {
  const HobbiesRow({
    required this.id,
    required this.resumeId,
    required this.isVisible,
    required this.sortOrder,
    this.name,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final bool isVisible;
  final num sortOrder;
  final String? name;
  final dynamic ar;
  final dynamic en;

  factory HobbiesRow.fromJson(Map<String, dynamic> json) {
    return HobbiesRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      isVisible: json['is_visible'] as bool? ?? false,
      sortOrder: (json['sort_order'] as num?) ?? 0,
      name: json['name'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'is_visible': isVisible,
      'sort_order': sortOrder,
      'name': name,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.address` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AddressRow {
  const AddressRow({
    required this.id,
    required this.resumeId,
    this.nationalAddress,
    this.ar,
    this.en,
  });

  final String id;
  final String resumeId;
  final String? nationalAddress;
  final dynamic ar;
  final dynamic en;

  factory AddressRow.fromJson(Map<String, dynamic> json) {
    return AddressRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      nationalAddress: json['national_address'] as String?,
      ar: json['ar'],
      en: json['en'],
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'national_address': nationalAddress,
      'ar': ar,
      'en': en,
    };
  }
}

/// Mirror of `public.templates` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class TemplatesRow {
  const TemplatesRow({
    required this.id,
    required this.name,
    this.nameAr,
    this.previewUrl,
    this.thumbnailUrl,
    required this.isPremium,
    required this.isActive,
    required this.category,
    this.tags,
    required this.sortOrder,
    this.descriptionAr,
    this.descriptionEn,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String name;
  final String? nameAr;
  final String? previewUrl;
  final String? thumbnailUrl;
  final bool isPremium;
  final bool isActive;
  final String category;
  final dynamic tags;
  final num sortOrder;
  final String? descriptionAr;
  final String? descriptionEn;
  final String createdAt;
  final String updatedAt;

  factory TemplatesRow.fromJson(Map<String, dynamic> json) {
    return TemplatesRow(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      nameAr: json['name_ar'] as String?,
      previewUrl: json['preview_url'] as String?,
      thumbnailUrl: json['thumbnail_url'] as String?,
      isPremium: json['is_premium'] as bool? ?? false,
      isActive: json['is_active'] as bool? ?? false,
      category: json['category'] as String? ?? '',
      tags: json['tags'],
      sortOrder: (json['sort_order'] as num?) ?? 0,
      descriptionAr: json['description_ar'] as String?,
      descriptionEn: json['description_en'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'name': name,
      'name_ar': nameAr,
      'preview_url': previewUrl,
      'thumbnail_url': thumbnailUrl,
      'is_premium': isPremium,
      'is_active': isActive,
      'category': category,
      'tags': tags,
      'sort_order': sortOrder,
      'description_ar': descriptionAr,
      'description_en': descriptionEn,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.subscriptions` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class SubscriptionsRow {
  const SubscriptionsRow({
    required this.id,
    required this.userId,
    this.stripeSubscriptionId,
    this.stripePriceId,
    this.stripeCustomerId,
    this.status,
    this.currentPeriodStart,
    this.currentPeriodEnd,
    required this.cancelAtPeriodEnd,
    required this.provider,
    this.trialEnd,
    this.canceledAt,
    this.currency,
    this.lastEventId,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String userId;
  final String? stripeSubscriptionId;
  final String? stripePriceId;
  final String? stripeCustomerId;
  final String? status;
  final String? currentPeriodStart;
  final String? currentPeriodEnd;
  final bool cancelAtPeriodEnd;
  final String provider;
  final String? trialEnd;
  final String? canceledAt;
  final String? currency;
  final String? lastEventId;
  final String createdAt;
  final String updatedAt;

  factory SubscriptionsRow.fromJson(Map<String, dynamic> json) {
    return SubscriptionsRow(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String? ?? '',
      stripeSubscriptionId: json['stripe_subscription_id'] as String?,
      stripePriceId: json['stripe_price_id'] as String?,
      stripeCustomerId: json['stripe_customer_id'] as String?,
      status: json['status'] as String?,
      currentPeriodStart: json['current_period_start'] as String?,
      currentPeriodEnd: json['current_period_end'] as String?,
      cancelAtPeriodEnd: json['cancel_at_period_end'] as bool? ?? false,
      provider: json['provider'] as String? ?? '',
      trialEnd: json['trial_end'] as String?,
      canceledAt: json['canceled_at'] as String?,
      currency: json['currency'] as String?,
      lastEventId: json['last_event_id'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'user_id': userId,
      'stripe_subscription_id': stripeSubscriptionId,
      'stripe_price_id': stripePriceId,
      'stripe_customer_id': stripeCustomerId,
      'status': status,
      'current_period_start': currentPeriodStart,
      'current_period_end': currentPeriodEnd,
      'cancel_at_period_end': cancelAtPeriodEnd,
      'provider': provider,
      'trial_end': trialEnd,
      'canceled_at': canceledAt,
      'currency': currency,
      'last_event_id': lastEventId,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.support_tickets` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class SupportTicketsRow {
  const SupportTicketsRow({
    required this.id,
    this.userId,
    required this.subject,
    required this.message,
    this.attachmentUrl,
    required this.status,
    this.adminNotes,
    this.assignedTo,
    required this.priority,
    this.lastAdminReplyAt,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String? userId;
  final String subject;
  final String message;
  final String? attachmentUrl;
  final String status;
  final String? adminNotes;
  final String? assignedTo;
  final String priority;
  final String? lastAdminReplyAt;
  final String createdAt;
  final String updatedAt;

  factory SupportTicketsRow.fromJson(Map<String, dynamic> json) {
    return SupportTicketsRow(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String?,
      subject: json['subject'] as String? ?? '',
      message: json['message'] as String? ?? '',
      attachmentUrl: json['attachment_url'] as String?,
      status: json['status'] as String? ?? '',
      adminNotes: json['admin_notes'] as String?,
      assignedTo: json['assigned_to'] as String?,
      priority: json['priority'] as String? ?? '',
      lastAdminReplyAt: json['last_admin_reply_at'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'user_id': userId,
      'subject': subject,
      'message': message,
      'attachment_url': attachmentUrl,
      'status': status,
      'admin_notes': adminNotes,
      'assigned_to': assignedTo,
      'priority': priority,
      'last_admin_reply_at': lastAdminReplyAt,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.support_ticket_messages` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class SupportTicketMessagesRow {
  const SupportTicketMessagesRow({
    required this.id,
    required this.ticketId,
    required this.authorType,
    required this.authorId,
    required this.body,
    this.attachmentUrl,
    required this.isInternal,
    required this.createdAt,
  });

  final String id;
  final String ticketId;
  final String authorType;
  final String authorId;
  final String body;
  final String? attachmentUrl;
  final bool isInternal;
  final String createdAt;

  factory SupportTicketMessagesRow.fromJson(Map<String, dynamic> json) {
    return SupportTicketMessagesRow(
      id: json['id'] as String? ?? '',
      ticketId: json['ticket_id'] as String? ?? '',
      authorType: json['author_type'] as String? ?? '',
      authorId: json['author_id'] as String? ?? '',
      body: json['body'] as String? ?? '',
      attachmentUrl: json['attachment_url'] as String?,
      isInternal: json['is_internal'] as bool? ?? false,
      createdAt: json['created_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'ticket_id': ticketId,
      'author_type': authorType,
      'author_id': authorId,
      'body': body,
      'attachment_url': attachmentUrl,
      'is_internal': isInternal,
      'created_at': createdAt,
    };
  }
}

/// Mirror of `public.ai_usage` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AiUsageRow {
  const AiUsageRow({
    required this.id,
    this.userId,
    this.resumeId,
    this.actionType,
    this.tokensUsed,
    this.costEstimateUsd,
    required this.isError,
    this.errorMessage,
    required this.createdAt,
  });

  final String id;
  final String? userId;
  final String? resumeId;
  final String? actionType;
  final num? tokensUsed;
  final num? costEstimateUsd;
  final bool isError;
  final String? errorMessage;
  final String createdAt;

  factory AiUsageRow.fromJson(Map<String, dynamic> json) {
    return AiUsageRow(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String?,
      resumeId: json['resume_id'] as String?,
      actionType: json['action_type'] as String?,
      tokensUsed: (json['tokens_used'] as num?),
      costEstimateUsd: (json['cost_estimate_usd'] as num?),
      isError: json['is_error'] as bool? ?? false,
      errorMessage: json['error_message'] as String?,
      createdAt: json['created_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'user_id': userId,
      'resume_id': resumeId,
      'action_type': actionType,
      'tokens_used': tokensUsed,
      'cost_estimate_usd': costEstimateUsd,
      'is_error': isError,
      'error_message': errorMessage,
      'created_at': createdAt,
    };
  }
}

/// Mirror of `public.resume_views` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class ResumeViewsRow {
  const ResumeViewsRow({
    required this.id,
    required this.resumeId,
    this.viewerIp,
    this.referrer,
    this.userAgent,
    required this.viewedAt,
  });

  final String id;
  final String resumeId;
  final String? viewerIp;
  final String? referrer;
  final String? userAgent;
  final String viewedAt;

  factory ResumeViewsRow.fromJson(Map<String, dynamic> json) {
    return ResumeViewsRow(
      id: json['id'] as String? ?? '',
      resumeId: json['resume_id'] as String? ?? '',
      viewerIp: json['viewer_ip'] as String?,
      referrer: json['referrer'] as String?,
      userAgent: json['user_agent'] as String?,
      viewedAt: json['viewed_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'resume_id': resumeId,
      'viewer_ip': viewerIp,
      'referrer': referrer,
      'user_agent': userAgent,
      'viewed_at': viewedAt,
    };
  }
}

/// Mirror of `public.email_log` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class EmailLogRow {
  const EmailLogRow({
    required this.id,
    this.userId,
    required this.toEmail,
    required this.template,
    this.providerMessageId,
    required this.status,
    this.error,
    this.metadata,
    required this.createdAt,
  });

  final String id;
  final String? userId;
  final String toEmail;
  final String template;
  final String? providerMessageId;
  final String status;
  final String? error;
  final dynamic metadata;
  final String createdAt;

  factory EmailLogRow.fromJson(Map<String, dynamic> json) {
    return EmailLogRow(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String?,
      toEmail: json['to_email'] as String? ?? '',
      template: json['template'] as String? ?? '',
      providerMessageId: json['provider_message_id'] as String?,
      status: json['status'] as String? ?? '',
      error: json['error'] as String?,
      metadata: json['metadata'],
      createdAt: json['created_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'user_id': userId,
      'to_email': toEmail,
      'template': template,
      'provider_message_id': providerMessageId,
      'status': status,
      'error': error,
      'metadata': metadata,
      'created_at': createdAt,
    };
  }
}

/// Mirror of `public.admin_users` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AdminUsersRow {
  const AdminUsersRow({
    required this.id,
    required this.email,
    required this.passwordHash,
    required this.role,
    this.totpSecret,
    this.totpVerifiedAt,
    required this.isActive,
    this.lastLoginAt,
    this.lastLoginIp,
    required this.failedLoginAttempts,
    this.lockedUntil,
    this.recoveryCodesGeneratedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String email;
  final String passwordHash;
  final String role;
  final String? totpSecret;
  final String? totpVerifiedAt;
  final bool isActive;
  final String? lastLoginAt;
  final String? lastLoginIp;
  final num failedLoginAttempts;
  final String? lockedUntil;
  final String? recoveryCodesGeneratedAt;
  final String createdAt;
  final String updatedAt;

  factory AdminUsersRow.fromJson(Map<String, dynamic> json) {
    return AdminUsersRow(
      id: json['id'] as String? ?? '',
      email: json['email'] as String? ?? '',
      passwordHash: json['password_hash'] as String? ?? '',
      role: json['role'] as String? ?? '',
      totpSecret: json['totp_secret'] as String?,
      totpVerifiedAt: json['totp_verified_at'] as String?,
      isActive: json['is_active'] as bool? ?? false,
      lastLoginAt: json['last_login_at'] as String?,
      lastLoginIp: json['last_login_ip'] as String?,
      failedLoginAttempts: (json['failed_login_attempts'] as num?) ?? 0,
      lockedUntil: json['locked_until'] as String?,
      recoveryCodesGeneratedAt: json['recovery_codes_generated_at'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'email': email,
      'password_hash': passwordHash,
      'role': role,
      'totp_secret': totpSecret,
      'totp_verified_at': totpVerifiedAt,
      'is_active': isActive,
      'last_login_at': lastLoginAt,
      'last_login_ip': lastLoginIp,
      'failed_login_attempts': failedLoginAttempts,
      'locked_until': lockedUntil,
      'recovery_codes_generated_at': recoveryCodesGeneratedAt,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.admin_sessions` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AdminSessionsRow {
  const AdminSessionsRow({
    required this.id,
    required this.adminId,
    required this.tokenHash,
    this.ip,
    this.userAgent,
    required this.createdAt,
    required this.lastSeenAt,
    required this.expiresAt,
    this.revokedAt,
  });

  final String id;
  final String adminId;
  final String tokenHash;
  final String? ip;
  final String? userAgent;
  final String createdAt;
  final String lastSeenAt;
  final String expiresAt;
  final String? revokedAt;

  factory AdminSessionsRow.fromJson(Map<String, dynamic> json) {
    return AdminSessionsRow(
      id: json['id'] as String? ?? '',
      adminId: json['admin_id'] as String? ?? '',
      tokenHash: json['token_hash'] as String? ?? '',
      ip: json['ip'] as String?,
      userAgent: json['user_agent'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      lastSeenAt: json['last_seen_at'] as String? ?? '',
      expiresAt: json['expires_at'] as String? ?? '',
      revokedAt: json['revoked_at'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'admin_id': adminId,
      'token_hash': tokenHash,
      'ip': ip,
      'user_agent': userAgent,
      'created_at': createdAt,
      'last_seen_at': lastSeenAt,
      'expires_at': expiresAt,
      'revoked_at': revokedAt,
    };
  }
}

/// Mirror of `public.admin_audit_log` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AdminAuditLogRow {
  const AdminAuditLogRow({
    required this.id,
    this.adminId,
    this.adminEmail,
    required this.action,
    this.targetType,
    this.targetId,
    this.metadata,
    this.ip,
    this.userAgent,
    required this.createdAt,
  });

  final String id;
  final String? adminId;
  final String? adminEmail;
  final String action;
  final String? targetType;
  final String? targetId;
  final dynamic metadata;
  final String? ip;
  final String? userAgent;
  final String createdAt;

  factory AdminAuditLogRow.fromJson(Map<String, dynamic> json) {
    return AdminAuditLogRow(
      id: json['id'] as String? ?? '',
      adminId: json['admin_id'] as String?,
      adminEmail: json['admin_email'] as String?,
      action: json['action'] as String? ?? '',
      targetType: json['target_type'] as String?,
      targetId: json['target_id'] as String?,
      metadata: json['metadata'],
      ip: json['ip'] as String?,
      userAgent: json['user_agent'] as String?,
      createdAt: json['created_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'admin_id': adminId,
      'admin_email': adminEmail,
      'action': action,
      'target_type': targetType,
      'target_id': targetId,
      'metadata': metadata,
      'ip': ip,
      'user_agent': userAgent,
      'created_at': createdAt,
    };
  }
}

/// Mirror of `public.admin_ip_allowlist` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AdminIpAllowlistRow {
  const AdminIpAllowlistRow({
    required this.id,
    required this.cidr,
    this.label,
    required this.isActive,
    this.createdBy,
    required this.createdAt,
  });

  final String id;
  final String cidr;
  final String? label;
  final bool isActive;
  final String? createdBy;
  final String createdAt;

  factory AdminIpAllowlistRow.fromJson(Map<String, dynamic> json) {
    return AdminIpAllowlistRow(
      id: json['id'] as String? ?? '',
      cidr: json['cidr'] as String? ?? '',
      label: json['label'] as String?,
      isActive: json['is_active'] as bool? ?? false,
      createdBy: json['created_by'] as String?,
      createdAt: json['created_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'cidr': cidr,
      'label': label,
      'is_active': isActive,
      'created_by': createdBy,
      'created_at': createdAt,
    };
  }
}

/// Mirror of `public.admin_notes` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AdminNotesRow {
  const AdminNotesRow({
    required this.id,
    this.adminId,
    this.adminEmail,
    required this.targetType,
    required this.targetId,
    required this.body,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String? adminId;
  final String? adminEmail;
  final String targetType;
  final String targetId;
  final String body;
  final String createdAt;
  final String updatedAt;

  factory AdminNotesRow.fromJson(Map<String, dynamic> json) {
    return AdminNotesRow(
      id: json['id'] as String? ?? '',
      adminId: json['admin_id'] as String?,
      adminEmail: json['admin_email'] as String?,
      targetType: json['target_type'] as String? ?? '',
      targetId: json['target_id'] as String? ?? '',
      body: json['body'] as String? ?? '',
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'admin_id': adminId,
      'admin_email': adminEmail,
      'target_type': targetType,
      'target_id': targetId,
      'body': body,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.admin_recovery_codes` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AdminRecoveryCodesRow {
  const AdminRecoveryCodesRow({
    required this.id,
    required this.adminId,
    required this.codeHash,
    required this.generatedAt,
    this.usedAt,
    this.usedIp,
    this.usedUserAgent,
  });

  final String id;
  final String adminId;
  final String codeHash;
  final String generatedAt;
  final String? usedAt;
  final String? usedIp;
  final String? usedUserAgent;

  factory AdminRecoveryCodesRow.fromJson(Map<String, dynamic> json) {
    return AdminRecoveryCodesRow(
      id: json['id'] as String? ?? '',
      adminId: json['admin_id'] as String? ?? '',
      codeHash: json['code_hash'] as String? ?? '',
      generatedAt: json['generated_at'] as String? ?? '',
      usedAt: json['used_at'] as String?,
      usedIp: json['used_ip'] as String?,
      usedUserAgent: json['used_user_agent'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'admin_id': adminId,
      'code_hash': codeHash,
      'generated_at': generatedAt,
      'used_at': usedAt,
      'used_ip': usedIp,
      'used_user_agent': usedUserAgent,
    };
  }
}

/// Mirror of `public.app_settings` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AppSettingsRow {
  const AppSettingsRow({
    required this.key,
    this.value,
    this.updatedBy,
    required this.updatedAt,
  });

  final String key;
  final dynamic value;
  final String? updatedBy;
  final String updatedAt;

  factory AppSettingsRow.fromJson(Map<String, dynamic> json) {
    return AppSettingsRow(
      key: json['key'] as String? ?? '',
      value: json['value'],
      updatedBy: json['updated_by'] as String?,
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'key': key,
      'value': value,
      'updated_by': updatedBy,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.featured_resumes` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class FeaturedResumesRow {
  const FeaturedResumesRow({
    required this.resumeId,
    required this.sortOrder,
    this.featuredBy,
    required this.featuredAt,
  });

  final String resumeId;
  final num sortOrder;
  final String? featuredBy;
  final String featuredAt;

  factory FeaturedResumesRow.fromJson(Map<String, dynamic> json) {
    return FeaturedResumesRow(
      resumeId: json['resume_id'] as String? ?? '',
      sortOrder: (json['sort_order'] as num?) ?? 0,
      featuredBy: json['featured_by'] as String?,
      featuredAt: json['featured_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'resume_id': resumeId,
      'sort_order': sortOrder,
      'featured_by': featuredBy,
      'featured_at': featuredAt,
    };
  }
}

/// Mirror of `public.announcements` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AnnouncementsRow {
  const AnnouncementsRow({
    required this.id,
    this.titleAr,
    this.titleEn,
    this.bodyAr,
    this.bodyEn,
    required this.severity,
    required this.isActive,
    this.startsAt,
    this.endsAt,
    this.createdBy,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String? titleAr;
  final String? titleEn;
  final String? bodyAr;
  final String? bodyEn;
  final String severity;
  final bool isActive;
  final String? startsAt;
  final String? endsAt;
  final String? createdBy;
  final String createdAt;
  final String updatedAt;

  factory AnnouncementsRow.fromJson(Map<String, dynamic> json) {
    return AnnouncementsRow(
      id: json['id'] as String? ?? '',
      titleAr: json['title_ar'] as String?,
      titleEn: json['title_en'] as String?,
      bodyAr: json['body_ar'] as String?,
      bodyEn: json['body_en'] as String?,
      severity: json['severity'] as String? ?? '',
      isActive: json['is_active'] as bool? ?? false,
      startsAt: json['starts_at'] as String?,
      endsAt: json['ends_at'] as String?,
      createdBy: json['created_by'] as String?,
      createdAt: json['created_at'] as String? ?? '',
      updatedAt: json['updated_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'title_ar': titleAr,
      'title_en': titleEn,
      'body_ar': bodyAr,
      'body_en': bodyEn,
      'severity': severity,
      'is_active': isActive,
      'starts_at': startsAt,
      'ends_at': endsAt,
      'created_by': createdBy,
      'created_at': createdAt,
      'updated_at': updatedAt,
    };
  }
}

/// Mirror of `public.ai_rate_limit_overrides` Postgres rows.
///
/// Generated from `packages/types/src/database.ts` — DO NOT EDIT BY HAND.
class AiRateLimitOverridesRow {
  const AiRateLimitOverridesRow({
    required this.userId,
    required this.dailyLimit,
    this.reason,
    this.adminId,
    this.expiresAt,
    required this.createdAt,
  });

  final String userId;
  final num dailyLimit;
  final String? reason;
  final String? adminId;
  final String? expiresAt;
  final String createdAt;

  factory AiRateLimitOverridesRow.fromJson(Map<String, dynamic> json) {
    return AiRateLimitOverridesRow(
      userId: json['user_id'] as String? ?? '',
      dailyLimit: (json['daily_limit'] as num?) ?? 0,
      reason: json['reason'] as String?,
      adminId: json['admin_id'] as String?,
      expiresAt: json['expires_at'] as String?,
      createdAt: json['created_at'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'user_id': userId,
      'daily_limit': dailyLimit,
      'reason': reason,
      'admin_id': adminId,
      'expires_at': expiresAt,
      'created_at': createdAt,
    };
  }
}
